azurerm_resource_group_name = "test-rg"
azurerm_resource_group_location = "East US"
azurerm_app_service_plan_name = "simple-plan"
Environment = "dev"
size = "F1"
azurerm_app_service_name = "aleti88-app"
